/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.BancoDeDados;
import model.Animais;

/**
 *
 * @author Gabriel
 */
public class cadastrarAnimais extends javax.swing.JInternalFrame {

    /**
     * Creates new form cadastrarAnimais
     */
    public cadastrarAnimais() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCadastroAnimais1 = new javax.swing.JPanel();
        jbNomeAnimal1 = new javax.swing.JLabel();
        jbIdadeAnimal1 = new javax.swing.JLabel();
        jbNLitrosLeite1 = new javax.swing.JLabel();
        spNlitros1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        tfNome1 = new javax.swing.JTextField();
        spIdade1 = new javax.swing.JSpinner();
        rdBtnSim1 = new javax.swing.JRadioButton();
        rdBtnNao1 = new javax.swing.JRadioButton();
        btnAddAnimal1 = new javax.swing.JButton();
        btnLimparCamposAnimais = new javax.swing.JButton();
        vaquinha = new javax.swing.JLabel();
        btnRetornar = new javax.swing.JButton();

        pnCadastroAnimais1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar Animais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jbNomeAnimal1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbNomeAnimal1.setText("Nome:");

        jbIdadeAnimal1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbIdadeAnimal1.setText("Idade:");

        jbNLitrosLeite1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbNLitrosLeite1.setText("Produção Leiteira diária(L):");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Vacinação:");

        rdBtnSim1.setText("Sim");

        rdBtnNao1.setText("Não");

        btnAddAnimal1.setText("Cadastrar");
        btnAddAnimal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAnimal1ActionPerformed(evt);
            }
        });

        btnLimparCamposAnimais.setText("Limpar Campos");
        btnLimparCamposAnimais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposAnimaisActionPerformed(evt);
            }
        });

        vaquinha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-vaca-50.png"))); // NOI18N

        btnRetornar.setText("Retornar");
        btnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetornarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCadastroAnimais1Layout = new javax.swing.GroupLayout(pnCadastroAnimais1);
        pnCadastroAnimais1.setLayout(pnCadastroAnimais1Layout);
        pnCadastroAnimais1Layout.setHorizontalGroup(
            pnCadastroAnimais1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadastroAnimais1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCadastroAnimais1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCadastroAnimais1Layout.createSequentialGroup()
                        .addGroup(pnCadastroAnimais1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbNomeAnimal1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(vaquinha))
                    .addGroup(pnCadastroAnimais1Layout.createSequentialGroup()
                        .addGroup(pnCadastroAnimais1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdBtnNao1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdBtnSim1)
                            .addComponent(jbIdadeAnimal1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spIdade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spNlitros1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbNLitrosLeite1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCadastroAnimais1Layout.createSequentialGroup()
                .addComponent(btnAddAnimal1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimparCamposAnimais))
            .addGroup(pnCadastroAnimais1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(btnRetornar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnCadastroAnimais1Layout.setVerticalGroup(
            pnCadastroAnimais1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadastroAnimais1Layout.createSequentialGroup()
                .addGroup(pnCadastroAnimais1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCadastroAnimais1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbNomeAnimal1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(vaquinha, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbNLitrosLeite1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spNlitros1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbIdadeAnimal1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spIdade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdBtnSim1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdBtnNao1)
                .addGap(18, 18, 18)
                .addGroup(pnCadastroAnimais1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimparCamposAnimais)
                    .addComponent(btnAddAnimal1))
                .addGap(18, 18, 18)
                .addComponent(btnRetornar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnCadastroAnimais1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnCadastroAnimais1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddAnimal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAnimal1ActionPerformed
        //Adicionando ANIMAIS no nosso Banco de Dados Externo que está no SqL
        
        //Conexão com o nosso BD feita pela classe BancoDeDados
        BancoDeDados BD=new BancoDeDados();
        //Criando um animal 
        Animais an=new Animais();
        //Cadastrando o animal
        an.setIdade((int)spIdade1.getValue());
        an.setNome(tfNome1.getText());
        if(rdBtnSim1.isSelected())
        {
            an.setVacinou("Sim!");
        }
        else{
            an.setVacinou("Não!");
        }
        an.setnLitros((int)spNlitros1.getValue());
        //Conectando o animal e o adicionando ao Banco de Dados
        BD.inserirAnimal(an);

    }//GEN-LAST:event_btnAddAnimal1ActionPerformed

    private void btnLimparCamposAnimaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposAnimaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparCamposAnimaisActionPerformed

    private void btnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnRetornarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAnimal1;
    private javax.swing.JButton btnLimparCamposAnimais;
    private javax.swing.JButton btnRetornar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jbIdadeAnimal1;
    private javax.swing.JLabel jbNLitrosLeite1;
    private javax.swing.JLabel jbNomeAnimal1;
    private javax.swing.JPanel pnCadastroAnimais1;
    private javax.swing.JRadioButton rdBtnNao1;
    private javax.swing.JRadioButton rdBtnSim1;
    private javax.swing.JSpinner spIdade1;
    private javax.swing.JSpinner spNlitros1;
    private javax.swing.JTextField tfNome1;
    private javax.swing.JLabel vaquinha;
    // End of variables declaration//GEN-END:variables
}
