/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.BancoDeDados;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 *
 * @author Gabriel
 */
public class Pesquisar extends javax.swing.JInternalFrame {

    /**
     * Creates new form Pesquisar
     */
    public Pesquisar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //Criando um objeto de Banco de Dados "Global"
    //Criando uma conexão com o BD
    BancoDeDados BD = new BancoDeDados();

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GruposDePesquisas = new javax.swing.ButtonGroup();
        ImagemPesquisa = new javax.swing.JLabel();
        Label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        rdnBtnVendas = new javax.swing.JRadioButton();
        rdnBtnProdutores = new javax.swing.JRadioButton();
        rdnBtnAnimais = new javax.swing.JRadioButton();
        btnConsultar = new javax.swing.JButton();
        listaInfos = new java.awt.List();
        Label3 = new javax.swing.JLabel();
        Label4 = new javax.swing.JLabel();
        rdnBtnEndereco = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        ImagemPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisar.png"))); // NOI18N

        Label1.setText("ID");

        label2.setText("Nome");

        GruposDePesquisas.add(rdnBtnVendas);
        rdnBtnVendas.setText("Vendas");

        GruposDePesquisas.add(rdnBtnProdutores);
        rdnBtnProdutores.setText("Produtores");

        GruposDePesquisas.add(rdnBtnAnimais);
        rdnBtnAnimais.setText("Animais");

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        listaInfos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaInfosActionPerformed(evt);
            }
        });

        GruposDePesquisas.add(rdnBtnEndereco);
        rdnBtnEndereco.setText("Endereco");

        jButton1.setText("Retornar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listaInfos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdnBtnProdutores)
                        .addGap(18, 18, 18)
                        .addComponent(rdnBtnEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsultar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdnBtnVendas)
                                .addGap(34, 34, 34)
                                .addComponent(rdnBtnAnimais))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label1)
                                .addGap(70, 70, 70)
                                .addComponent(label2)
                                .addGap(26, 26, 26)
                                .addComponent(Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Label4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ImagemPesquisa, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ImagemPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label1)
                            .addComponent(label2))
                        .addComponent(Label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Label4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listaInfos, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdnBtnVendas)
                    .addComponent(rdnBtnAnimais)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdnBtnProdutores)
                    .addComponent(btnConsultar)
                    .addComponent(rdnBtnEndereco)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Lista que usarei para fazer as consultas

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:

        //Limpando a lista antes de acessar os valores 
        listaInfos.clear();
        //Consultando nossos produtores
        if (rdnBtnProdutores.isSelected()) {
            Label1.setText("CPF");
            label2.setText("Nome");
            Label3.setText("Idade");
            //Fazendo a pesquisa com todos os produtores possíveis
            for (int i = 0; i <BD.buscarProdutoresSemFiltro().size(); i++) 
            {
                if(BD.buscarProdutoresSemFiltro().get(i)!=null)
                {
                    this.listaInfos.add(BD.buscarProdutoresSemFiltro().get(i).getCpf() +
                            " | "+BD.buscarProdutoresSemFiltro().get(i).getNome()+" | "+BD.buscarProdutoresSemFiltro().get(i).getIdade());
                }
            }
        }
        //Consultando os animais adicionados
        
        if(rdnBtnAnimais.isSelected())
        {
            //Mudando os labels
            Label1.setText("Nome");
            label2.setText("idade");
            Label3.setText("Produção diária(L)");
            Label4.setText("Vacinou");
            
            //Fazendo a pesquisa com todos os animais possíveis 
            for (int i = 0; i <BD.buscarAnimaisSemFiltro().size(); i++) {
                //Verificando se os animais estão com valores preenchidos
                if(BD.buscarAnimaisSemFiltro().get(i)!=null)
                {
                    this.listaInfos.add(BD.buscarAnimaisSemFiltro().get(i).getNome()
                            +" |                 "+BD.buscarAnimaisSemFiltro().get(i).getIdade()
                            +" |                 "+BD.buscarAnimaisSemFiltro().get(i).getnLitros()
                    +" |                         "+BD.buscarAnimaisSemFiltro().get(i).getVacinou());
                }
            }
        }
        //Consultando as Vendas Realizadas
        if(rdnBtnVendas.isSelected())
        {
            Label1.setText("Nome Comprador");
            label2.setText("CPF Comprador");
            Label3.setText("Data Compra");
            Label4.setText("Valor  Número de Peças");
            //Fazendo a pesquisa com todos as vendas possiveis
            for (int i = 0; i <BD.buscarVendasSemFiltro().size(); i++) {
                //Verificando se os animais estão com valores preenchidos
                if(BD.buscarVendasSemFiltro().get(i)!=null)
                {
                    this.listaInfos.add(BD.buscarVendasSemFiltro().get(i).getNome()+
                            " |                         "+BD.buscarVendasSemFiltro().get(i).getCpf()+" |                 "
                            +BD.buscarVendasSemFiltro().get(i).getData()+" |                      "+
                            BD.buscarVendasSemFiltro().get(i).getQuantVendas()
                            +" |        "+BD.buscarVendasSemFiltro().get(i).getValor());
                }
            }
        }
        if(rdnBtnEndereco.isSelected())
        {
            //Pesquisando os endereços dos produtores
                        //Fazendo a pesquisa com todos as vendas possiveis
            for (int i = 0; i <BD.buscarEnderecoSemFiltro().size(); i++) {
                //Verificando se os animais estão com valores preenchidos
                if(BD.buscarEnderecoSemFiltro().get(i)!=null)
                {
                    this.listaInfos.add(BD.buscarEnderecoSemFiltro().get(i).getId()
                            +" | "+BD.buscarEnderecoSemFiltro().get(i).getPais()
                            +" | "+BD.buscarEnderecoSemFiltro().get(i).getCidade()
                            +" | "+BD.buscarEnderecoSemFiltro().get(i).getRua()
                            +" | "+BD.buscarEnderecoSemFiltro().get(i).getNumero()
                            +" | "+BD.buscarEnderecoSemFiltro().get(i).getComplemento());
                }
                else{
                    this.listaInfos.add("Não informado");
                }
            }
            
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void listaInfosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaInfosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaInfosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GruposDePesquisas;
    private javax.swing.JLabel ImagemPesquisa;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel label2;
    private java.awt.List listaInfos;
    private javax.swing.JRadioButton rdnBtnAnimais;
    private javax.swing.JRadioButton rdnBtnEndereco;
    private javax.swing.JRadioButton rdnBtnProdutores;
    private javax.swing.JRadioButton rdnBtnVendas;
    // End of variables declaration//GEN-END:variables
}
