/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Frame;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JLabel;
import model.Produtor;

/**
 *
 * @author Gabriel
 */
public class telaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipla
     */
    public telaPrincipal() {
        initComponents();
    }
    DefaultListModel dlm = new DefaultListModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        telaInterna = new javax.swing.JDesktopPane();
        jDesktopCadastro = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        jDesktopInfos = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        itmCadastar = new javax.swing.JMenu();
        itmCadProdutor = new javax.swing.JMenuItem();
        itmVendasCad = new javax.swing.JMenuItem();
        itmAnimaisCad = new javax.swing.JMenuItem();
        itmPesquisar = new javax.swing.JMenu();
        itmPesq = new javax.swing.JMenuItem();
        itmDeletar = new javax.swing.JMenu();
        deletarInfos = new javax.swing.JMenuItem();
        itmAtualizar = new javax.swing.JMenu();
        AtualizarInfos = new javax.swing.JMenuItem();
        itmSobre = new javax.swing.JMenu();
        itmSobre2 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("jMenu5");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gerenciamento"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Operações"));

        telaInterna.setBackground(new java.awt.Color(240, 240, 240));
        telaInterna.setMaximumSize(new java.awt.Dimension(318, 370));

        javax.swing.GroupLayout jDesktopCadastroLayout = new javax.swing.GroupLayout(jDesktopCadastro);
        jDesktopCadastro.setLayout(jDesktopCadastroLayout);
        jDesktopCadastroLayout.setHorizontalGroup(
            jDesktopCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );
        jDesktopCadastroLayout.setVerticalGroup(
            jDesktopCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        telaInterna.setLayer(jDesktopCadastro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout telaInternaLayout = new javax.swing.GroupLayout(telaInterna);
        telaInterna.setLayout(telaInternaLayout);
        telaInternaLayout.setHorizontalGroup(
            telaInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopCadastro)
        );
        telaInternaLayout.setVerticalGroup(
            telaInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopCadastro)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaInterna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaInterna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jDesktopInfos.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jDesktopInfosLayout = new javax.swing.GroupLayout(jDesktopInfos);
        jDesktopInfos.setLayout(jDesktopInfosLayout);
        jDesktopInfosLayout.setHorizontalGroup(
            jDesktopInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );
        jDesktopInfosLayout.setVerticalGroup(
            jDesktopInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopInfos)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopInfos)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        itmCadastar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/application_add.png"))); // NOI18N
        itmCadastar.setText("Cadastrar");
        itmCadastar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastarActionPerformed(evt);
            }
        });

        itmCadProdutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/group_add.png"))); // NOI18N
        itmCadProdutor.setText("Produtor");
        itmCadProdutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itmCadProdutorMouseClicked(evt);
            }
        });
        itmCadProdutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadProdutorActionPerformed(evt);
            }
        });
        itmCadastar.add(itmCadProdutor);

        itmVendasCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/coins_add.png"))); // NOI18N
        itmVendasCad.setText("Vendas");
        itmVendasCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmVendasCadActionPerformed(evt);
            }
        });
        itmCadastar.add(itmVendasCad);

        itmAnimaisCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        itmAnimaisCad.setText("Animais");
        itmAnimaisCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAnimaisCadActionPerformed(evt);
            }
        });
        itmCadastar.add(itmAnimaisCad);

        jMenuBar1.add(itmCadastar);

        itmPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/zoom.png"))); // NOI18N
        itmPesquisar.setText("Pesquisar");

        itmPesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/zoom_in.png"))); // NOI18N
        itmPesq.setText("Pesquisas");
        itmPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmPesqActionPerformed(evt);
            }
        });
        itmPesquisar.add(itmPesq);

        jMenuBar1.add(itmPesquisar);

        itmDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/database_delete.png"))); // NOI18N
        itmDeletar.setText("Deletar");

        deletarInfos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cross.png"))); // NOI18N
        deletarInfos.setText("Excluir registros");
        deletarInfos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarInfosActionPerformed(evt);
            }
        });
        itmDeletar.add(deletarInfos);

        jMenuBar1.add(itmDeletar);

        itmAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/database_edit.png"))); // NOI18N
        itmAtualizar.setText("Atualizar");
        itmAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAtualizarActionPerformed(evt);
            }
        });

        AtualizarInfos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/world_edit.png"))); // NOI18N
        AtualizarInfos.setText("Atualizar Dados");
        AtualizarInfos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarInfosActionPerformed(evt);
            }
        });
        itmAtualizar.add(AtualizarInfos);

        jMenuBar1.add(itmAtualizar);

        itmSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/infos.png"))); // NOI18N
        itmSobre.setText("Informações");
        itmSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSobreActionPerformed(evt);
            }
        });

        itmSobre2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/infos.png"))); // NOI18N
        itmSobre2.setText("Sobre o projeto");
        itmSobre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSobre2ActionPerformed(evt);
            }
        });
        itmSobre.add(itmSobre2);

        jMenuBar1.add(itmSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Criando fora para  testar
    cadastrarVendas telaVendas = new cadastrarVendas();
    ProdutorInterno telaCadProdutor = new ProdutorInterno();
    private void itmCadProdutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadProdutorActionPerformed
        // TODO add your handling code here:
        telaInterna.add(telaCadProdutor);
        telaCadProdutor.setVisible(true);
    }//GEN-LAST:event_itmCadProdutorActionPerformed

    private void itmVendasCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmVendasCadActionPerformed
        // TODO add your handling code here:
        cadastrarVendas v = new cadastrarVendas();
        this.telaInterna.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_itmVendasCadActionPerformed

    private void itmCadProdutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itmCadProdutorMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_itmCadProdutorMouseClicked

    private void itmCadastarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastarActionPerformed
        // TODO add your handling code here:
        ProdutorInterno p = new ProdutorInterno();
        this.telaInterna.add(p);
        p.setVisible(true);

    }//GEN-LAST:event_itmCadastarActionPerformed

    private void itmAnimaisCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAnimaisCadActionPerformed
        // TODO add your handling code here:
        cadastrarAnimais a = new cadastrarAnimais();
        this.telaInterna.add(a);
        a.setVisible(true);
    }//GEN-LAST:event_itmAnimaisCadActionPerformed

    private void itmPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmPesqActionPerformed
        // TODO add your handling code here:

        Pesquisar pesq = new Pesquisar();
        this.jDesktopInfos.add(pesq);
        pesq.setVisible(true);
    }//GEN-LAST:event_itmPesqActionPerformed

    private void itmSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSobreActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_itmSobreActionPerformed

    private void itmSobre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSobre2ActionPerformed
        // TODO add your handling code here:
        Sobre sob = new Sobre();
        this.jDesktopInfos.add(sob);
        sob.setVisible(true);
    }//GEN-LAST:event_itmSobre2ActionPerformed

    private void deletarInfosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarInfosActionPerformed
        // TODO add your handling code here:
        DeletarInformações del=new DeletarInformações();
        this.telaInterna.add(del);
        del.setVisible(true);
    }//GEN-LAST:event_deletarInfosActionPerformed

    private void itmAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAtualizarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_itmAtualizarActionPerformed

    private void AtualizarInfosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarInfosActionPerformed

       //Incluindo a tela de atualização na tela de operações
       AtualizarInfos up=new AtualizarInfos();
       this.telaInterna.add(up);
       up.setVisible(true);
    }//GEN-LAST:event_AtualizarInfosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AtualizarInfos;
    private javax.swing.JMenuItem deletarInfos;
    private javax.swing.JMenuItem itmAnimaisCad;
    private javax.swing.JMenu itmAtualizar;
    private javax.swing.JMenuItem itmCadProdutor;
    private javax.swing.JMenu itmCadastar;
    private javax.swing.JMenu itmDeletar;
    private javax.swing.JMenuItem itmPesq;
    private javax.swing.JMenu itmPesquisar;
    private javax.swing.JMenu itmSobre;
    private javax.swing.JMenuItem itmSobre2;
    private javax.swing.JMenuItem itmVendasCad;
    private javax.swing.JDesktopPane jDesktopCadastro;
    private javax.swing.JDesktopPane jDesktopInfos;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JDesktopPane telaInterna;
    // End of variables declaration//GEN-END:variables

    private void verficaFrames(ProdutorInterno telaCadProdutor, cadastrarVendas telaVendas) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
